// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using kaadebug_bff_api.Infrastructure;
using kaadebug_bff_api.Models;

#nullable disable

namespace kaadebug_bff_api.Migrations
{
    [DbContext(typeof(PlantCareDbContext))]
    [Migration("20260815200945_AddCascadeDeleteToSensorReadings")]
    partial class AddCascadeDeleteToSensorReadings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "connection_status", new[] { "NOTFOUND", "OFFLINE", "ONLINE", "UNASSOCIATED" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "connection_status", "connection_status", new[] { "ONLINE", "OFFLINE", "UNASSOCIATED", "NOTFOUND" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "health_status", new[] { "CRITICAL", "HEALTHY", "WARNING" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "health_status", "health_status", new[] { "HEALTHY", "WARNING", "CRITICAL" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "notification_priority", new[] { "HIGH", "LOW", "MEDIUM" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "notification_priority", "notification_priority", new[] { "LOW", "MEDIUM", "HIGH" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "sensor_type", new[] { "AIR_HUMIDITY", "LUMINOSITY", "SOIL_MOISTURE", "TEMPERATURE" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "sensor_type", "sensor_type", new[] { "SOIL_MOISTURE", "AIR_HUMIDITY", "TEMPERATURE", "LUMINOSITY" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("kaadebug_bff_api.Models.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<ConnectionStatus>("ConnectionStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("connection_status")
                        .HasDefaultValue(ConnectionStatus.Unassociated)
                        .HasColumnName("connection_status");

                    b.Property<DateTime?>("LastHeartbeatAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_heartbeat_at");

                    b.Property<Guid?>("PlantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RegisteredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("registered_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("devices", (string)null);
                });

            modelBuilder.Entity("kaadebug_bff_api.Models.DiagnosisResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsHealthy")
                        .HasColumnType("boolean")
                        .HasColumnName("is_healthy");

                    b.Property<JsonDocument>("IssuesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("issues_json");

                    b.Property<string>("OverallObservation")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("overall_observation");

                    b.Property<DateTime>("PerformedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("performed_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("PlantId")
                        .HasColumnType("uuid")
                        .HasColumnName("plant_id");

                    b.HasKey("Id");

                    b.HasIndex("PlantId");

                    b.ToTable("diagnosis_results", (string)null);
                });

            modelBuilder.Entity("kaadebug_bff_api.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("message");

                    b.Property<Guid>("PlantId")
                        .HasColumnType("uuid")
                        .HasColumnName("plant_id");

                    b.Property<NotificationPriority>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("notification_priority")
                        .HasDefaultValue(NotificationPriority.Low)
                        .HasColumnName("priority");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("PlantId");

                    b.HasIndex("UserId");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("kaadebug_bff_api.Models.Plant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<HealthStatus>("HealthStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("health_status")
                        .HasDefaultValue(HealthStatus.Healthy)
                        .HasColumnName("health_status");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("photo_url");

                    b.Property<Guid>("SpeciesId")
                        .HasColumnType("uuid")
                        .HasColumnName("species_id");

                    b.Property<string>("StatusReason")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("status_reason");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .IsUnique();

                    b.HasIndex("SpeciesId");

                    b.HasIndex("UserId");

                    b.ToTable("plants", (string)null);
                });

            modelBuilder.Entity("kaadebug_bff_api.Models.SensorReading", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<bool>("IsWithinIdealRange")
                        .HasColumnType("boolean")
                        .HasColumnName("is_within_ideal_range");

                    b.Property<Guid>("PlantId")
                        .HasColumnType("uuid")
                        .HasColumnName("plant_id");

                    b.Property<DateTime>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<SensorType>("SensorType")
                        .HasColumnType("sensor_type")
                        .HasColumnName("sensor_type");

                    b.Property<decimal>("Value")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("PlantId", "ReadAt")
                        .HasDatabaseName("ix_sensor_readings_plant_id_read_at");

                    b.ToTable("sensor_readings", (string)null);
                });

            modelBuilder.Entity("kaadebug_bff_api.Models.Species", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("AirHumidityMax")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("air_humidity_max");

                    b.Property<decimal>("AirHumidityMin")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("air_humidity_min");

                    b.Property<JsonDocument>("CareInfo")
                        .HasColumnType("jsonb")
                        .HasColumnName("care_info");

                    b.Property<decimal>("LuminosityMax")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("luminosity_max");

                    b.Property<decimal>("LuminosityMin")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("luminosity_min");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("photo_url");

                    b.Property<decimal>("SoilMoistureMax")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("soil_moisture_max");

                    b.Property<decimal>("SoilMoistureMin")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("soil_moisture_min");

                    b.Property<decimal>("TemperatureMax")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("temperature_max");

                    b.Property<decimal>("TemperatureMin")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("temperature_min");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("species", (string)null);
                });

            modelBuilder.Entity("kaadebug_bff_api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("CriticalAlertsOnly")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("critical_alerts_only");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<bool>("NotificationsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("notifications_enabled");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_hash");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("kaadebug_bff_api.Models.DiagnosisResult", b =>
                {
                    b.HasOne("kaadebug_bff_api.Models.Plant", "Plant")
                        .WithMany("DiagnosisResults")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_diagnosis_results_plant");

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("kaadebug_bff_api.Models.Notification", b =>
                {
                    b.HasOne("kaadebug_bff_api.Models.Plant", "Plant")
                        .WithMany("Notifications")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_plant");

                    b.HasOne("kaadebug_bff_api.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_user");

                    b.Navigation("Plant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("kaadebug_bff_api.Models.Plant", b =>
                {
                    b.HasOne("kaadebug_bff_api.Models.Device", "Device")
                        .WithOne("Plant")
                        .HasForeignKey("kaadebug_bff_api.Models.Plant", "DeviceId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_plants_device");

                    b.HasOne("kaadebug_bff_api.Models.Species", "Species")
                        .WithMany("Plants")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_plants_species");

                    b.HasOne("kaadebug_bff_api.Models.User", "User")
                        .WithMany("Plants")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_plants_user");

                    b.Navigation("Device");

                    b.Navigation("Species");

                    b.Navigation("User");
                });

            modelBuilder.Entity("kaadebug_bff_api.Models.SensorReading", b =>
                {
                    b.HasOne("kaadebug_bff_api.Models.Device", "Device")
                        .WithMany("SensorReadings")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sensor_readings_device");

                    b.HasOne("kaadebug_bff_api.Models.Plant", "Plant")
                        .WithMany("SensorReadings")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sensor_readings_plant");

                    b.Navigation("Device");

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("kaadebug_bff_api.Models.Device", b =>
                {
                    b.Navigation("Plant");

                    b.Navigation("SensorReadings");
                });

            modelBuilder.Entity("kaadebug_bff_api.Models.Plant", b =>
                {
                    b.Navigation("DiagnosisResults");

                    b.Navigation("Notifications");

                    b.Navigation("SensorReadings");
                });

            modelBuilder.Entity("kaadebug_bff_api.Models.Species", b =>
                {
                    b.Navigation("Plants");
                });

            modelBuilder.Entity("kaadebug_bff_api.Models.User", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("Plants");
                });
#pragma warning restore 612, 618
        }
    }
}
